### PR TITLE
Add social icons to the footer (#14)

### PR DESCRIPTION
**Pull request by MuhammadAshraf23**
### Description:
This pull request implements social media icons in the footer section of the website to enhance user engagement and provide quick access to our social media profiles.

### Changes made:

Added social media icons (Facebook, Twitter, LinkedIn, etc.) to the footer.
Ensured the icons are responsive and align with the overall footer design.
Updated the CSS styles to improve icon appearance and hover effects.
### References:

This change addresses issue #14.
### Testing:

Verified that the icons are correctly displayed across different screen sizes.
Confirmed that links direct to the respective social media pages.

### CODE REVIEW

**Comment by Artemiskgg1** [comment]
@MuhammadAshraf23 This PR has conflicts with the base branch.
Please resolve them

**Comment by MuhammadAshraf23** [comment]
> @MuhammadAshraf23 This PR has conflicts with the base branch. Please resolve them

Ok

**Comment by MuhammadAshraf23** [comment]
@Artemiskgg1 if you need any changes then ask.

**Comment by Artemiskgg1** [comment]
> @Artemiskgg1 If you need any changes, please let me know.

This branch has conflicts with the main branch. Please resolve them

**Comment by MuhammadAshraf23** [comment]
> > @Artemiskgg1 If you need any changes, please let me know.
> 
> This branch has conflicts with the main branch. Please resolve them

@Artemiskgg1 Done

**Comment by MuhammadAshraf23** [comment]
@Artemiskgg1 can you tell me  why you unmerged

**Comment by Artemiskgg1** [comment]
@MuhammadAshraf23 This branch still has conflicts as you can see as well.
I have added the hacktoberfest-accepted label on your PR.
I cannot merge if there are conficts.

**Comment by MuhammadAshraf23** [comment]
> @MuhammadAshraf23 This branch still has conflicts as you can see as well. I have added the hacktoberfest-accepted label on your PR. I cannot merge if there are conficts.
@Artemiskgg1 
Thank you for the update. I will review the conflicts and resolve them as soon as possible. Once I've done that, I will let you know so we can proceed with the merge. I appreciate your patience!

**Comment by Artemiskgg1** [comment]
Yeah sure! Ping me, I'll reopen this PR

**Pull request closed without merging**
