### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by pushtisonawala**
#3 
image
Plzz merge

### CODE REVIEW

**Comment by Artemiskgg1** [comment]
@pushtisonawala I think the original theme of the website looked better. Can you change the navbar without changing the hero section padding.
image
This design has to be followed

**Review by Artemiskgg1 — CHANGES_REQUESTED** [review]
@pushtisonawala I think the original theme of the website looked better. Can you change the navbar without changing the hero section padding.
image
This design has to be followed

**Comment by pushtisonawala** [comment]
can u pls allow me to change the padding, i will make some changes and it will look better

**Comment by pushtisonawala** [comment]
is the navbar looking fine ?? I will readjust the padding of the hero to appear the same as original @Artemiskgg1

**Pull request closed without merging**
